spring:
  rabbitmq:
    host: s4.java21.net
    port: 5672
    username: admin
    password: nhnacademy123!
    virtual-host: ink_local
    dynamic: false
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
