spring:
  application:
    name: ink3-batch
  config:
    import: optional:configserver:https://ink3.shop/config/
  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: s4.java21.net
    port: 5672
    username: admin
    password: nhnacademy123!
    virtual-host: ink_dev

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh
